//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerPongTracker.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSetting
    {
        public int GameSettingId { get; set; }
        public int GameId { get; set; }
        public int SettingId { get; set; }
        public string Value { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Setting Setting { get; set; }
    }
}
